site_name: "PyMoX Doc"
site_url: "https://PyMoX-fr.github.io"
site_description: "Doc de PyMoX-fr"
repo_name: "PyMoX-fr"
repo_url: "https://github.com/PyMoX-fr/PyMoX-fr.github.io"
# edit_uri_template: "edit/main/docs/"
edit_uri: "edit/main/docs/"
site_author: "Communauté PyMoX"
copyright: |
  <b>PyMoX</b> | Copyright © 1 990 - 2 025 - <b>Communauté PyMoX - FRANCE</b>

# Contenu généré depuis les paramètres de votre espace gitlab à ne pas modifier
# site_name: !ENV [CI_PROJECT_TITLE, "Version locale du site"]
# site_url: !ENV [CI_PAGES_URL, "http://127.0.0.1:8000/"]
# site_author: !ENV [CI_PROJECT_ROOT_NAMESPACE, USERNAME]
# repo_url: !ENV [CI_PROJECT_URL]  # pour avoir le lien vers le dépôt

# docs_dir: docs

#nav:  Inutile avec l'utilisation des fichiers .pages plus pratiques

theme:
  language: fr

  # logo: assets/images/logo.svg
  # favicon: assets/images/animated_favicon.gif
  favicon: assets/images/favicon.ico
  # logo: assets/images/animated_favicon.gif
  logo: assets/images/pymox_logo_tr_001.png
  name: pyodide-mkdocs-theme
  show_cache_refresh: true
  # name: material  # 👀 pour la validation
  # custom_dir: pyodide-mkdocs-theme  # 👈 ton vrai thème  # ✅ thème installé via pip, reconnu par mkdocs

  # playground:
  #   include: null
  # ide: false

  ## name: material
  ##   features:
  ##       - navigation.instant   # /!\ Cette option est incompatible avec le thème !

  # palette:        # Palettes de couleurs jour/nuit
  #   - media: "(prefers-color-scheme: light)"
  #     scheme: default
  #     primary: orange
  #     accent: deep orange
  #     toggle:
  #       icon: material/weather-sunny
  #       name: Passer au mode nuit
  #   - media: "(prefers-color-scheme: dark)"
  #     scheme: slate
  #     primary: orange
  #     accent: deep orange
  #     toggle:
  #       icon: material/weather-night
  #       name: Passer au mode jour

  features:
    #- navigation.instant  !! Obligatoire à supprimer
    #- navigation.tabs   suppression pour avoir le menu vertical
    # - navigation.instant
    - navigation.top
    - toc.integrate
    # - content.action.edit # Bouton edit page orinin
    - header.autohide
    - content.code.annotate # Pour les annotations de code deroulantes avec +
    - content.code.copy # Ajout après MAJ pour pouvoir copier du code
  custom_dir: includes/overrides

markdown_extensions:
  - md_in_html
  - abbr

  - def_list # Les listes de définition.
  - attr_list # Un peu de CSS et des attributs HTML.
  - footnotes # Notes[^1] de bas de page.  [^1]: ma note.
  - admonition # Blocs colorés  !!! info "ma remarque"
  - pymdownx.details #   qui peuvent se plier/déplier.
  - pymdownx.caret # Passage ^^souligné^^ ou en ^exposant^.
  - pymdownx.mark # Passage ==surligné==.
  - pymdownx.tilde # Passage ~~barré~~ ou en ~indice~.
  - pymdownx.highlight: # Coloration syntaxique du code
      auto_title: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite # pour  `#!python  <python en ligne>`
  - pymdownx.snippets # Inclusion de fichiers externe.
  - pymdownx.tasklist: # Cases à cocher  - [ ]  et - [x]
      custom_checkbox: false #   avec cases d'origine
      clickable_checkbox: true #   et cliquables.
  - pymdownx.tabbed: # Volets glissants.  === "Mon volet"
      alternate_style: true
      # slugify: !!python/object/apply:pymdownx.slugs.slugify
      #   kwds:
      #     case: lower

  - pymdownx.keys: # Touches du clavier.  ++ctrl+d++
      separator: "\uff0b"
  - pymdownx.emoji: # Émojis  :boom:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  # - pymdownx.blocks.admonition
  # - pymdownx.blocks.details
  - pymdownx.blocks.details:
      types:
        - name: unreleased-block
          class: unreleased-block

  # - pymdownx.blocks:

  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
          
        # Option pour désactiver le label "Text Only"
        # - pymdownx.blocks:
        #     details:
        #       text_only_label: false

  - pymdownx.arithmatex:
      generic: true

  - pymdownx.striphtml:
      strip_js_on_attributes: false # !!REQUIS!!
      strip_attributes: "" # !!REQUIS!!

  - toc:
      permalink: ⚓︎
      toc_depth: 3
      separator: "_"

extra:
  version:
    provider: mike
    default: latest
  author: Communauté PyMoX
  description: Documentation de PyMoX-fr
  keywords: Python, Programmation, Tutoriel, Didacticiel, Formation, Apprentissage, Cours, Exercices, Jeux, Vidéo-jeux, JEU DE ROLLE, RPG, Role Playing Game, Jeu de rôle
  image: assets/images/pymox_logo_tr
  social:
    # - icon: fontawesome/solid/clipboard-question
    #   link: https://forge.apps.education.fr/docs/modeles/site-web-cours-general/-/issues
    #   name: Poser une question par ticket

    - icon: fontawesome/brands/wikipedia-w
      link: https://fr.wikipedia.org
      name: L'encyclopédie libre que chacun peut améliorer

    # [ ] fix icon discord
    # - icon: fontawesome/solid/discord
    #   link: mailto:grcote7l@gmail.com
    #   name: Écrire à l'auteur

    # - icon: fontawesome/solid/
    #   link: mailto:grcote7l@gmail.com
    #   name: Écrire à l'auteur

  # macros_dir: docs/xtra/macros

plugins:
  - awesome-pages:
      collapse_single_pages: true

  - search
  - open-in-new-tab:
      add_icon: true

  # module_name: macros.qcm_macros
  # modules:
  # - pyodide_macros.macros
  # - exclude-search
  #   ...
  # - tags:
  #     tags_file: tags.md # Déprécié
  - tags
  
  # - mkdocs-material
  # - mkdocs-pymdownx
  
  - pyodide_macros:
      # Vous pouvez ajouter ici tout réglage que vous auriez ajouté concernant les macros:
      on_error_fail: true # Il est conseillé d'ajouter celui-ci si vous ne l'utilisez pas.
      build:
        # python_libs:
        #   - turtle
        tab_to_spaces: 4
        # - git-revision-date-localized # 2see à tester git-revision-date-localized
      # - sqlite-console
      # module_name: macros_pymox/one_citation_a_day
      module_name:
        ppp_macros_pymox # ppp_ = dossier provisoire en attendant de réussir à glisser ces macros dans includes/macros_pymox/
        # - macros_pymox/one_citation_a_day
        # - macros_pymox.all_citations
      # modules:
      #   - ./macros_pymox/one_citation_a_day
      # - macros_pymox.all_citations
  # - changelog: [ ] to do
  #     file: docs/changelog.yml
      
  # - macros:

# En remplacement de mkdocs-exclude. Tous les fichiers correspondant aux patterns indiqués seront
# exclu du site final et donc également de l'indexation de la recherche.
# Nota: ne pas mettre de commentaires dans ces lignes !
exclude_docs: |
  **/*_REM.md
  **/*.py
  - gc7/

extra_javascript:
  - xtra/javascripts/removeTrashBtn.js
  # - xtra/javascripts/essai.js
  - xtra/javascripts/copy.js

extra_css:
  - xtra/stylesheets/essais.css # ajustements
  - xtra/stylesheets/ajustements.css # ajustements
