name: Deploy Docs (CRON à ≃ 3h00)

on:
  schedule:
    - cron: "0 1 * * *" # Tous les jours à 3h (GMT) du matin
    # - cron: '0 * * * *' # Toutes les heures
    # - cron: '*/15 * * * *' # Toutes les 15 minutes
    # - cron: "*/5 * * * *" # Toutes les 5 minutes
jobs:
  daily-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: 🛠️ Installer MkDocs + plugins
        run: |
          pip install --upgrade pip
          pip install mkdocs mkdocs-material pyodide-mkdocs-theme mkdocs-awesome-pages-plugin mkdocs-open-in-new-tab
      - name: 🌐 Prépare le fichier CNAME
        run: echo "pymox.fr" > docs/CNAME
      - name: ⏱️ Build CRON silencieux
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHA: ${{ github.sha }}
        run: |
          DEPLOY_INFO_DIR="docs/outils/logs"
          DEPLOY_INFO_FILE="deploy_info.md"
          DEPLOY_INFO_PATH="$DEPLOY_INFO_DIR/$DEPLOY_INFO_FILE"

          mkdir -p "$(dirname "$DEPLOY_INFO_PATH")"
          # mkdir -p "$DEPLOY_INFO_PATH"

          DATE_HUMAN="$(TZ='Europe/Paris' date '+%d/%m/%Y')"
          TIME_HUMAN="$(TZ='Europe/Paris' date '+%H:%M:%S')"
          DATE_ISO="$(date -u '+%Y-%m-%dT%H:%M:%SZ')"
          DATE_UNIX="$(date +%s)"
          MSG="⏱️ Déploiement automatique CRON"
          AUTOR="PyMoX"

          echo "# ⏱️ Dernier déploiement" > "$DEPLOY_INFO_PATH"
          echo "" >> "$DEPLOY_INFO_PATH"

          echo "## → Automatique" >> "$DEPLOY_INFO_PATH"
          echo "" >> "$DEPLOY_INFO_PATH"

          echo "| 📅 Date        | 🕰️ Heure (Paris)       | 🌐 ISO 8601 UTC         | 🔢 Timestamp UNIX |" >> "$DEPLOY_INFO_PATH"
          echo "|----------------|------------------------|------------------------|--------------------|" >> "$DEPLOY_INFO_PATH"
          echo "| **$DATE_HUMAN**  | **$TIME_HUMAN**        | \`$DATE_ISO\`   | \`$DATE_UNIX\`       |" >> "$DEPLOY_INFO_PATH"
          echo "" >> "$DEPLOY_INFO_PATH"

          
          echo "### 📋 Informations de déploiement" >> "$DEPLOY_INFO_PATH"
          echo "" >> "$DEPLOY_INFO_PATH"
          echo "📝 Message Git : **${MSG}**<br>" >> "$DEPLOY_INFO_PATH"
          echo "👤 Auteur : ${AUTOR}<br>" >> "$DEPLOY_INFO_PATH"
          echo "🔁 SHA Commit : \`${SHA}\`<br>" >> "$DEPLOY_INFO_PATH"
          echo "🚀 **Déclencheur** : GitHub Actions" >> "$DEPLOY_INFO_PATH"
          echo "<br><br>" >> "$DEPLOY_INFO_PATH"

          echo "> ✅ Ce déploiement a été enclenché **automatiquement** comme chaque nuit vers 4h (G.M.T.)." >> "$DEPLOY_INFO_PATH"

          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add "$DEPLOY_INFO_PATH"
          git commit -m "⏱️ Déploiement quotidien CRON ($DATE_HUMAN - $TIME_HUMAN)"
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
          git push

      - name: 🌐 Ajoute le fichier CNAME + déploiement
        run: |
          echo "pymox.fr" > docs/CNAME
          mkdocs gh-deploy --force

          # Créer un tag automatiquement:
          #   git tag -a "cron-deploy-$(date +%Y%m%d%H%M)" -m "Déploiement CRON automatique"

          # 🔍 Écriture dans le fichier logs selon le type de commit
          # if [[ "$MSG" == ⏱️* ]]; then
          #   echo "Dernier commit (AUTO pour rebuild): $DATE" >> "$LOGS_FILE"
          # else
          #   echo "Commit ($MSG < $AUTOR - Manual Push): $DATE" >> "$LOGS_FILE"
          # fi

          # 🤖 Si c'est un déclenchement CRON
          # if [[ "${{ github.event_name }}" == "schedule" ]]; then
