name: Deploy Docs

on:
  push:
    branches: [main]
  schedule:
    # - cron: '0 3 * * *' # Tous les jours à 3 H (AM)
    # - cron: '0 * * * *' # Toutes les heures
    # - cron: '*/5 * * * *' # Toutes les 5 minutes
    - cron: '*/15 * * * *' # Toutes les 15 minutes
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: 🛠️ Installer les dépendances MkDocs
        run: |
          pip install --upgrade pip
          pip install mkdocs mkdocs-material pyodide-mkdocs-theme mkdocs-awesome-pages-plugin

      - name: 📋 Push si CRON, mets à jour deploy_info.md et build-log.txt
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          DATE="$(TZ='Europe/Paris' date '+%d/%m/%Y - %H:%M:%S')"
          MSG="$(git log -1 --pretty=%B)"
          AUTOR="$(git log -1 --pretty=%an)"
          SHA="${{ github.sha }}"
          
          LOGS_FILE="tools/logs/build-log.txt"
          
          echo "🚀 Déploiement déclenché par le commit suivant :"
          echo "📅 Date      : $DATE
          echo "🗒️ Message   : $MSG
          echo "👤 Auteur    : $AUTOR
          echo "🔢 SHA       : $SHA

          echo "# 🛠️ Déploiement MkDocs" > docs/deploy-info.md
          echo "" >> docs/deploy-info.md
          echo "| 🗓️ **Dernier build** | $DATE |" >> docs/deploy-info.md
          echo "|----------------------|--------|" >> docs/deploy-info.md
          echo "| 📝 **Message**        | $MSG  |" >> docs/deploy-info.md
          echo "| 👤 **Auteur**         | $AUTOR |" >> docs/deploy-info.md
          echo "| 🔢 **Commit SHA**     | \`$SHA\` |" >> docs/deploy-info.md
          echo "" >> docs/deploy-info.md
          # echo "---" >> docs/deploy-info.md
          echo "> Ce build a été généré automatiquement par le workflow GitHub Actions." >> docs/deploy-info.md
          echo "> Pour plus d'infos sur les déclenchements, voir le fichier \`build-log.txt\`." >> docs/deploy-info.md


          if [[ "$MSG" == ⏱️* ]]; then
            echo "Dernier commit (AUTO pour rebuild): $DATE" >> "$LOGS_FILE"
          else
            echo "Commit ($MSG < $AUTOR): $DATE" >> "$LOGS_FILE"
          fi

          if [[ "${{ github.event_name }}" == "schedule" ]]; then
            # Configuration Git
            git config --global user.email "action@github.com"
            git config --global user.name "GitHub Action"

            # Pour focer le commùit pour avoir fichier log mis à jour
            # Ajout et commit
            git add "$LOGS_FILE"
            git commit -m "⏱️ Rebuild automatique CRON ($DATE)"
            git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
            git push
          else
            echo "Commit ($MSG < $AUTOR): $DATE" >> "$LOGS_FILE"
            
            # Configuration Git
            git config --global user.email "action@github.com"
            git config --global user.name "GitHub Action"

            # Ajout et commit
            git add build-log.txt
            git commit -m "⏱️ Rebuild automatique CRON ($DATE)"
            git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
            git push
          fi
          
          # Pour voir la création du fichier logs
          ls -la tools/logs
          cat "$LOGS_FILE"

          mkdocs gh-deploy --force

          # Créer un tag automatiquement:
          #   git tag -a "cron-deploy-$(date +%Y%m%d%H%M)" -m "Déploiement CRON automatique"

